[package]
name = "broadcast"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
termcolor = "1.1"
whoami="1.2"
nix="0.23"