name: Release

on:
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix: 
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Rename
      run: mv target/release/broadcast broadcast-${{ matrix.os }}
    - uses: softprops/action-gh-release@0.1.14
      with:
        files: broadcast-${{ matrix.os }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
