name: Release

on: [release]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix: 
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - uses: yakuhzi/action-release@v1
      with:
        file: /target/release/broadcast
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
